src/types/endpoint.ts
=> Add CDN Endpoints

src/managers/base.ts, src/managers/channels.ts, src/managers/emojis.ts, src/models/cacheAdapter.ts, src/models/client.ts, src/models/commandClient.ts, src/models/extensions.ts, src/models/rest.ts, src/structures/guild.ts, src/structures/member.ts, src/structures/message.ts, src/structures/webhook.ts, src/types/gateway.ts, src/types/guild.ts, src/types/voice.ts, src/utils/collection.ts
English grammer is too hard... lol
=> fix: minor grammar/typo fixes in comments

src/utils/colorutil.ts
- Supports all Discord.JS color and CSS color
- Some color utility methods
```js
// embed
.setColor(ColorUtil.resolveColor("RANDOM"))
```
=> Add ColorUtil

src/managers/base.ts, src/managers/channels.ts, src/managers/guildVoiceStates.ts, src/managers/members.ts, src/managers/messageReactions.ts, src/managers/messages.ts, src/managers/presences.ts, src/test/index.ts
This pr fixes managers' array function.
Fixed bug: Some structures need more args than just client and data, and most managers' array function didn't pass those args.
=> Fix managers' array function

mod.ts, src/gateway/handlers/guildIntegrationsUpdate.ts, src/managers/guildChannels.ts, src/structures/guildCategoryChannel.ts, src/structures/guildNewsChannel.ts, src/structures/guildVoiceChannel.ts, src/structures/textChannel.ts, src/test/index.ts, src/types/channel.ts, src/utils/getChannelByType.ts
This PR adds channel edit feature. I was surprised that channel edit feature wasn't developed.
=> Add channel edit feature

src/structures/template.ts, src/types/template.ts
- Added Template structure
- Added helper methods to the template structure
- Updated the Template Discord API types
=> feat: add template structure and methods

src/gateway/index.ts
Just a refactor, nothing much...
=> refactor(gateway): use switch-case to avoid repetitive code

README.md, src/models/client.ts, src/models/rest.ts, src/models/slashClient.ts, src/structures/message.ts, src/structures/textChannel.ts, src/test/music.ts, src/test/slash-only.ts, src/types/guild.ts, src/types/slash.ts
Adds utility method for HTTP-based Slash Commands, and also helper methods for Opine and Oak framework.
Along with that, updated types for Member Screening feature. And added SlashBuilder, GuildTextChannel#bulkDelete and TextChannel#fetchMessages.
=> feat: HTTP based Slash Commands util

src/structures/role.ts, src/types/role.ts
=> feat: add Role#tags prop

src/managers/base.ts, src/managers/guildChannels.ts, src/managers/invites.ts, src/managers/memberRoles.ts, src/managers/members.ts, src/managers/messageReactions.ts, src/managers/roles.ts, src/models/client.ts
This PR adds some missing methods to interact with REST API.
=> feat: new rest methods

.gitignore, src/gateway/handlers/index.ts, src/models/cacheAdapter.ts, src/models/client.ts, src/models/command.ts, src/models/extensions.ts, src/models/shard.ts, src/structures/member.ts, src/test/cmds/addemoji.ts, src/types/channel.ts, src/types/endpoint.ts, src/utils/delay.ts, src/utils/intents.ts
Parameter name was wrong in JSDoc fixed it.
=> Fix JSDoc, typo and using before initialization.

src/structures/guild.ts
Since, there was no way of checking if guild is "complete". I added this, kinda hacky sollution tbh.
=> Guild awaitAvailiable method and removing redundant code in guild structure

src/types/slash.ts
THIS PR CAN BE MERGED AFTER "https://github.com/discord/discord-api-docs/pull/2408" IS MERGED
=> fix: add permissions field to InteractionPayload#member

mod.ts, src/gateway/handlers/index.ts, src/models/client.ts, src/models/collectors.ts, src/models/rest.ts, src/structures/webhook.ts, src/test/index.ts, src/test/music.ts, src/test/slash.ts
This PR adds support for some new options and implements Collectors too.
=> new options & collectors

mod.ts, src/gateway/handlers/guildMemberRemove.ts, src/gateway/handlers/messageDeleteBulk.ts, src/gateway/handlers/messageReactionRemove.ts, src/gateway/handlers/voiceStateUpdate.ts, src/managers/base.ts, src/managers/guildChannels.ts, src/managers/guildEmojis.ts, src/managers/guilds.ts, src/managers/memberRoles.ts, src/managers/roles.ts, src/models/collectors.ts, src/structures/guild.ts, src/structures/message.ts, src/structures/role.ts, src/test/cmd.ts, src/test/index.ts, src/types/guild.ts, src/types/role.ts
This pr adds missing guild implementations (which are written in #86).
If you want to check what things are implemented right now, check #86.
=> Add Missing Guild Implementations

mod.ts, src/managers/guilds.ts, src/managers/roles.ts, src/models/client.ts, src/models/rest.ts, src/models/slashClient.ts, src/structures/guild.ts, src/structures/role.ts, src/structures/user.ts, src/test/guild.ts, src/test/template.ts, src/test/user.ts, src/types/guild.ts, src/utils/snowflake.ts
This PR fixes sync template url and adds some useful functions(like `<User>.createDM()`, `<Role>.addTo(<Member>)`).
=> Fix Some Bugs and Add Some Useful Things

src/gateway/handlers/guildEmojiUpdate.ts, src/gateway/handlers/index.ts, src/gateway/handlers/reconnect.ts, src/structures/application.ts, src/structures/base.ts, src/structures/channel.ts, src/structures/embed.ts, src/structures/emoji.ts, src/structures/guild.ts, src/structures/member.ts, src/structures/message.ts, src/structures/messageSticker.ts, src/structures/presence.ts, src/structures/role.ts, src/structures/slash.ts, src/structures/textChannel.ts, src/structures/user.ts, src/types/channel.ts, src/utils/bitfield.ts, src/utils/permissions.ts, src/utils/snowflake.ts
And some changes I don't remember.
=> Add SnowflakeBase, useful methods for permissions to GuildTextChannel, and jsdoc in a lot of places

deps.ts, examples/ping.ts, src/models/slashClient.ts, test/mod.ts
- Removes useless deps of Opine and Oak frameworks.
- Adds basic /test
- Try to not depend on direct github URLs.
=> Remove Opine and Oak deps

src/managers/base.ts, src/managers/baseChild.ts, src/test/index.ts
example:
```ts
for await (const role of Member.roles) {
// do stuff
}
```
=> add Async Interator support for Managers

src/gateway/handlers/guildCreate.ts, src/gateway/handlers/guildDelete.ts, src/models/rest.ts, src/structures/textChannel.ts, src/test/index.ts, src/utils/err_fmt.ts
- Fixes addReaction and removeReaction.
- Better formatted REST Errors.
- Adds caching emojis at guildCreate.
=> fix(rest): addReaction and removeReaction not working with custom emojis

src/structures/embed.ts
This PR adds embed validation to the `toJSON()` method of the Embed class. This makes it easier for users.
=> feat: add embed validation

src/rest/request.ts, test/index.ts
=> fix(rest): change body to query in get or delete

.github/PULL_REQUEST_TEMPLATE.md
=> More natural expression

src/managers/members.ts, src/rest/endpoints.ts
This adds the `/guilds/{guild.id}/members/search` endpoint.
=> add search for guild members endpoint

mod.ts, src/structures/application.ts, src/structures/team.ts, src/types/application.ts, src/types/team.ts
Added [team](https://discord.com/developers/docs/topics/teams#data-models-team-object) to harmony
=> feat: team

src/gateway/handlers/mod.ts, src/interactions/mod.ts, src/interactions/tsxComponents.ts, src/managers/channels.ts, src/structures/interactions.ts, src/structures/messageComponents.ts, src/types/channel.ts, src/types/messageComponents.ts, test/test.tsx, test/trigger.ts, tsconfig.json
=> feat(interactions/message_components): support tsx for creating components

src/managers/messages.ts
=> fix: guild not being present on Message when using MessagesManager#get

examples/webhook.ts
=> add webhook on examples folder

src/managers/channels.ts, src/structures/message.ts, src/structures/textChannel.ts, test/index.ts
This PR adds features like:
- Pin a message
- Unpin a message
- Get all pinned messages in the channel
and closes #203
=> feat (message): add features related to message pins

src/structures/threadChannel.ts, src/types/channel.ts
=> fix(threads): add missing props

README.md
=> Dj be making typos

.gitignore, src/commands/client.ts, src/commands/command.ts, test/middleware.ts
you can find an example in `test/middleware.ts`
fix #173
=> feat(commands): add support for middlewares

src/managers/channels.ts, src/structures/interactions.ts, src/types/channel.ts
=> feat: support multiple embeds and deprecate single embed option

src/commands/client.ts, src/gateway/handlers/mod.ts
A command not found event, useful for easily handling commands that are not defined without crashing the bot
=> feat(CommandClient): commandNotFound event

src/commands/command.ts
Added description to CommandCategory
=> Add description to CommandCategory

deploy.ts, src/interactions/client.ts, src/interactions/decorators.ts, test/autocomplete.ts
=> feat(interactions/client): autocomplete handler

src/utils/oauthURL.ts
=> fix(util): createOAuthURL returning invalid url

src/structures/webhook.ts, test/webhook.ts
=> feat(structures/Webhook): support sending multiple files

.github/workflows/deno.yml, src/structures/channel.ts, src/structures/message.ts, src/structures/textChannel.ts, src/utils/channelTypes.ts
=> fix(structures): circular import

types/src/invites/mod.ts
This PR adds every type in [invite types](https://discord.com/developers/docs/resources/invite).
=> feat(v3/types): add every invite category types

types/src/guilds/guild.ts, types/src/stageInstances/mod.ts, types/src/stageInstances/stage.ts
This PR adds every [stage instance types](https://discord.com/developers/docs/resources/stage-instance)
=> 🏷️ feat(v3/types): add every stage instance types

types/src/channels/message.ts, types/src/stickers/sticker.ts
This PR adds every type in [sticker category](https://discord.com/developers/docs/resources/sticker).
=> 🏷️ feat(v3/types): add every sticker category types

scripts/setup.sh, types/src/stickers/mod.ts, types/src/voices/mod.ts, types/src/voices/voice.ts
This PR adds every type in [voice category](https://discord.com/developers/docs/resources/voice).
=> 🏷️ feat(v3/types): add every voice category types

src/commands/client.ts, src/commands/command.ts
=> feat: Add `optionalArgs` property to commands

types/src/applications/application.ts, types/src/applications/mod.ts, types/src/applications/team.ts, types/src/invites/intive.ts
This PR adds every type in [application types](https://discord.com/developers/docs/resources/application).
=> 🏷️ feat(v3/types): add every application types

examples/slash.ts
I saw some random typos, so I fixed them
=> fix random typos in slash example

src/client/client.ts
=> fix: use filtered collectors instead of all collectors

src/structures/guildVoiceChannel.ts, src/types/channel.ts, src/types/guild.ts, src/utils/channel.ts, src/utils/channelTypes.ts
This PR makes harmony support text in voice channel and closes #260. I don't know if text in voice channel has some differences with the implementation of text-based channels though.
=> ✨ feat: support text in voice channel (Closes #260)

src/interactions/decorators.ts
This pull request fixes autocomplete handler for slash commands group
=> Fix autocomplete decorator

src/interactions/client.ts, src/structures/member.ts
Same as #364 but I fixed the lint and format failing
Closes #364
=> Fix: Fix: correctly handle resolved member objects in interactions payload over http 

src/structures/presence.ts, src/types/presence.ts
Changes the way `CUSTOM_STATUS` is sent to discord to allow bots to utilize it
=> Feat: Add custom status support
