src/models/rest.ts, src/structures/message.ts, src/structures/textChannel.ts, src/types/channel.ts
In this PR, I have,
- Implemented Inline Replies (refer to https://github.com/discord/discord-api-docs/pull/2118). `Message#reply` was changed to use Inline Replies instead, but keep in mind - this feature is slowly rolling out, so it may throw 403 - Missing Access!
- Fixed unexpected behavior with REST Manager. Now handles status codes correctly.
=> feature: Inline Replies

src/structures/guild.ts
when use ban, module will raise error at everytime. this commit fix it.
----
+ `res.status` is always undefined and it makes raise error everytime. need to use `res.response.status`
=> fix ban feature

mod.ts, src/gateway/handlers/ready.ts, src/models/client.ts, src/models/command.ts, src/models/commandClient.ts, src/models/extensions.ts, src/structures/guildVoiceChannel.ts, src/structures/message.ts, src/test/class.ts
In this PR, I have added support for two decorators: event and command, and also changed argument parsing method from just split to CLI-like arguments.
- Fixed multiple prefix collisions.
- Reworked prefix handler.
- Added `Command#nsfw` and appropriate checks.
- Implemented sub-prefixes!
- Sub-prefix can be determined by Extensions.
- These can greatly help in distinguishing Extension commands from others.
- These can also serve as a way to make sub commands!
At the moment, decorators are only supported for class and its props/methods. So for using them, user must extend `Client` / `CommandClient`.
These decorators optionally accept event name when you don't want to keep method name same as the event. And these are applicable in `Client` (and `CommandClient`) and `Extension` too.
```ts …
```
=> feat(decorators): added support for decorated events and commands

src/utils/collection.ts
This PR changes the `first()`, `last()` and `random()` of `Harmony.Collection` (based on `@discordjs/collection`)
Added optional parameter `n` that takes the number of items to return.
Example: `Collection.first(10)`, `Collection.first()`
Added optional parameter `n` that takes the number of items to return.
Example: `Collection.last(10)`, `Collection.last()`
Added optional parameter `n` that takes the number of items to return.
Example: `Collection.random(10)`, `Collection.random()`
=> update collection methods

src/structures/message.ts, src/structures/messageSticker.ts, src/test/index.ts, src/types/channel.ts
This PR adds support for the sticker message and fixes to #62.
Currently, Discord only supports reading stickers (At least for bots).
https://discord.com/developers/docs/resources/channel#message-object-message-sticker-structure
=> Add Sticker Feature (related to #62)

src/gateway/index.ts, src/models/client.ts, src/models/rest.ts, src/models/slashClient.ts, src/test/music.ts, src/test/slash-only.ts
- This PR adds APIMap for easier API requests and customizable version.
- SlashClient and RESTManager can now be used alone without any Client or gateway connection for REST usage and handlers
- Also added Client#fetchApplication method.
- There are some breaking changes with SlashClient construction.
=> SlashClient & RESTManager can run alone and added APIMap

src/gateway/handlers/index.ts, src/models/client.ts, src/test/index.ts
This PR changes the way that does event typing and adds `<Client>.waitFor` method.
And since event typing works differently than before, it now supports autocomplete event names.
=> Change the event typing way and add <Client>.waitFor method

src/gateway/handlers/channelDelete.ts, src/gateway/handlers/guildCreate.ts, src/gateway/handlers/guildDelete.ts, src/gateway/handlers/guildRoleDelete.ts, src/gateway/handlers/index.ts, src/gateway/handlers/inviteDelete.ts, src/gateway/handlers/messageDelete.ts, src/gateway/index.ts, src/managers/channels.ts, src/managers/guildChannels.ts, src/managers/guildVoiceStates.ts, src/managers/invites.ts, src/managers/messageReactions.ts, src/managers/reactionUsers.ts, src/models/cacheAdapter.ts, src/models/client.ts, src/models/commandClient.ts, src/models/slashClient.ts, src/structures/groupChannel.ts, src/structures/guild.ts, src/structures/invite.ts, src/structures/textChannel.ts, src/test/chunk.ts, src/test/slash-only.ts, src/types/endpoint.ts
This PR introduces following changes,
- \*\_DELETE events now use Manager#_delete to avoid making REST API calls through some Managers (not any atm, but in future)
- Full Invite support added - create, delete, fetch Invites.
- Added a lot of more missing REST Methods to interact with API.
- Fixed Guild#chunk
- New event: guildLoaded
- Fixed GuildChannelsManager#array
- Fixed some more things.
=> Quick fix for Events to use Manager#_delete and adding full Invite support

src/gateway/handlers/index.ts, src/gateway/handlers/ready.ts, src/gateway/handlers/resume.ts, src/gateway/index.ts, src/models/client.ts, src/models/extensions.ts, src/models/shard.ts, src/models/slashClient.ts, src/structures/guild.ts, src/structures/guildVoiceChannel.ts, src/test/cmd.ts, src/test/index.ts, src/test/slash.ts
- This PR adds sharding support. All bots are auto sharded and can be disabled by `shardCount: 1` in client options
- Actually, just adds a ShardManager and queue for Identify. ShardManager just creates multiple `Gateway`s.
=> feat: sharding support

src/gateway/handlers/applicationCommandCreate.ts, src/gateway/handlers/applicationCommandDelete.ts, src/gateway/handlers/applicationCommandUpdate.ts, src/gateway/handlers/index.ts, src/gateway/handlers/ready.ts, src/models/client.ts, src/models/slashClient.ts, src/types/gateway.ts
literally title, though, adds following new events:
- `slashCommandCreate`
- `slashCommandUpdate`
- `slashCommandDelete`
ref: https://github.com/discord/discord-api-docs/pull/2367
=> add APPLICATION_COMMAND_* events

src/models/rest.ts
The name of the files may not be unique at all times, there occurs an instance where the name of the file may be the same; however, Discord will not regard the second item of the form data if any two items have the same key.
=> fix(models/rest): unique key for form data item

deps.ts, src/test/index.ts
I've updated deps.ts to use my fork of denoflate instead of the original one which downloads WASM each time Harmony code is run.. which is.. lol.
=> Use a fork of Denoflate to have cache-able WASM

src/utils/bitfield.ts
Passing a `string` or `string[]` as a resolvable to `BitField.has()` would not resolve the bit coming in for comparison, which means it would always return `false`. Porting [this missing line from Discord.JS](https://github.com/discordjs/discord.js/blob/master/src/util/BitField.js#L45) (which is all this PR does) should fix the issue.
=> fix(BitField): resolve the bit before checking

src/models/client.ts
When `Client#token` was set and the token parameter was passed to `Client#connect()`, the module would throw an 'No Token Provided' error.
This change makes this function prioritize the parameter over `Client#token`.
=> Fix Client#connect()'s logic to prioritize the token parameter over Client#token

src/managers/base.ts, src/managers/baseChild.ts, src/managers/channels.ts, src/models/command.ts, src/models/commandClient.ts, src/structures/textChannel.ts, src/test/index.ts, src/types/channel.ts
Currently, its not possible to send message to a channel which is not cached. This is a limitation and needs to be removed. Only workaround was using `client.rest`. Now, I've added `ChannelsManager#sendMessage` and `editMessage` which can simply take channel ID too. `TextChannel#send` now depends on this new method.
=> add ChannelsManager#{sendMessage, editMessage} and Command#onError

src/managers/guildChannelVoiceStates.ts, src/managers/guildVoiceStates.ts, src/structures/guildVoiceChannel.ts, src/structures/member.ts, src/structures/voiceState.ts, src/test/cmds/kickFromSpecificVoice.ts, src/test/cmds/kickFromVoice.ts
This PR:
- Adds `<VoiceState>.disconnect()`, `<VoiceState>.moveChannel()`, etc.
- Adds `<Member>.disconnectVoice()`, `<Member>.moveVoiceChannel()`, etc.
- Makes `<GuildVoiceStatesManager>` replace the guild as the manager's guild if it's undefined
- Adds `<GuildChannelVoiceStatesManager>` and `<VoiceChannel>.voiceStates` property
=> Add things to `<VoiceState>` and Add `<GuildChannelVoiceStatesManager>`

deploy.ts
There being no timers in Deploy runtime, REST doesn't work at all. For now, I added a check if they don't exist add dummy functions. Better than it not starting up in Deploy at all.
=> fix slash commands in deploy

mod.ts, src/commands/client.ts, src/commands/command.ts, src/utils/command.ts, test/argsparser_test.ts
Implements the feature request of #134
Not done!
=> Argument parsing for commands

src/utils/command.ts, test/argsparser_test.ts
Fixes cases like this where no rest value is provided but it doesn't use `defaultValue`
```ts
const messageArgs5: string[] = ['<@!708544768342229012>']
const expectedResult5 = {
user: '708544768342229012',
reason: 'No reason provided'
}
const commandArgs5: Args[] = [
{
name: 'user',
match: 'mentionUser'
},
{
name: 'reason',
match: 'rest',
defaultValue: 'No reason provided'
}
]
```
Added a test for it aswell
=> FIX(command) incorrect value for rest default value

src/utils/command.ts, test/argsparser_test.ts
Add filter function for match type content
=> Add filter function to `match: "content"`

src/utils/command.ts, test/argsparser_test.ts
adds ID parsing support for args
i don't know what i'm doing
One thing I think should be added as well but I thought was too breaking for some people's code was changing mentionX to just X (eg: mentionUser -> user)
- [possible] This PR introduces some Breaking changes.
=> id support for args

src/client/client.ts, src/client/shard.ts, src/gateway/handlers/guildCreate.ts, src/gateway/handlers/guildDelete.ts, src/gateway/handlers/mod.ts, src/gateway/handlers/ready.ts, src/gateway/mod.ts, src/structures/guild.ts, src/types/gateway.ts, src/types/guild.ts
This PR changes how `ready` works.
Current `ready` was just when shard received READY, but now it waits for all guilds to be loaded first.
Previous ready is now available in `shardReady` event instead.
Also fixes a bug where ready flushed guilds loaded by other shards..
=> feat: change ready event logic

src/client/client.ts
This pr fixes a race condition where `ready` event is already dispatched but client adds the listener after the event is fired.
because if this we are waiting for an event that does not get fire under normal circumstances
=> fix(client) Race condition

src/structures/interactions.ts
so that it returns the current object type (extending class) instead of only that which causes to cast each time in chain expressions
=> fix(interactions): return type -> this instead of complete type name

src/cache/adapter.ts, src/cache/default.ts, src/cache/redis.ts, src/client/client.ts, src/gateway/handlers/guildBanAdd.ts, src/gateway/handlers/guildBanRemove.ts, src/gateway/handlers/guildCreate.ts, src/gateway/handlers/guildEmojiUpdate.ts, src/gateway/handlers/guildMemberAdd.ts, src/gateway/handlers/guildMemberRemove.ts, src/gateway/handlers/guildMemberUpdate.ts, src/gateway/handlers/messageReactionAdd.ts, src/gateway/handlers/messageUpdate.ts, src/gateway/handlers/presenceUpdate.ts, src/gateway/mod.ts, src/interactions/slashCommand.ts, src/managers/base.ts, src/managers/baseChild.ts, src/managers/channels.ts, src/managers/guildChannelVoiceStates.ts, src/managers/guildChannels.ts, src/managers/guildEmojis.ts, src/managers/guilds.ts, src/managers/memberRoles.ts, src/managers/members.ts, src/managers/messages.ts, src/managers/presences.ts
- adds optimized .size methods to managers and child managers
- adds .memberCacheSize to GuildsManager and .messageCacheSize to ChannelsManager
- fixes user not being cached from member object and duplication of user object in member objects
- added per channel message cache limit and corresponding option
- added option to disable compression
there are some breaking changes for cache adapter too, though
tested bot on 300 guilds
before: 100mb+ usage
now: 20mb~ usage
=> feat: optimize cache

src/structures/interactions.ts
Added missing `?` so `Interaction.send(...)` does not throw, when passing only a string.
Fixes #178
=> Fix #178 Interaction.send() throws if passed a string

src/structures/webhook.ts
This makes a change to fix a bug in Harmony, so now you can have webhooks send a message with the avatar URL.
This doesn't change the API at all
- [✓] These changes have been tested against Discord API or do not contain API change.
=> Fix minor bug with webhooks so you can send with the avatar

src/structures/interactions.ts
`InteractionResponse.flags` ignored when sending response with `type = 5`. This caused `Interaction.defer(true)` to not behave as intended (did not send ephemeral message). I've added the missing check for `InteractionResponseType.DEFERRED_CHANNEL_MESSAGE`.
btw, I've not created an issue before making a pull request (as opposed to my last contribution) because I was gonna fix it myself anyway. If in the future you want me to always create an issue beforehand just let me know; it just seemed like a waste of time.
=> Fix not being able to respond with ephemeral message

mod.ts
This enum is used to filter on type for fetching the audit log of a guild, but the enum itself is not exposed through `mod.ts`. This PR adds AuditLogEvents to the exported types.
=> Expose AuditLogEvents

src/structures/guild.ts
The `AuditLogPayload` type returned by the `Guild#fetchAuditLog()` function did not match the actual structure of the data. The `AuditLog` type *did* contain the correct structure but was unused. This PR fixes these issues by assigning and returning the correct type within `fetchAuditLog`.
=> Fix audit log typing

src/client/client.ts
I noticed that there was a spelling mistake in the client options docs, so I fixed it.
=> fix 1 spelling mistake

src/interactions/slashCommand.ts, src/types/slashCommands.ts, test/slash-builder.ts, test/slash-only.ts, test/slash.ts
`SlashBuilder` drops the description field from an option when the type was SUB_COMMAND or SUB_COMMAND_GROUP. This would cause the API to return an error when uploading the slash commands because [`description` is a required field](https://discord.com/developers/docs/interactions/slash-commands#application-command-object-application-command-option-structure).
This PR drops the removal of `description`, so that groups and subcommands can be created through the builder.
I also fixed the slash.ts and slash-only.ts tests as I used them for testing before making slash-builder.ts
```
PUT https://discord.com/api/v8/applications/329830967328112651/guilds/202898980223451136/commands returned 400
(50035) Invalid Form Body
at 0.options[0].description:
- BASE_TYPE_REQUIRED: This field is required
at …
```
=> fix: Keep description for slash groups and subcommands.

src/commands/client.ts, src/commands/command.ts
Closes #182 
Introduces a `onMissingArgs` method to `Command` and does the appropriate changes to make it work, this allows for more granular missing arg responses
=> Add `onMissingArgs` method to `Command`

src/commands/client.ts, src/commands/command.ts
~~Makes the `author` property on `CommandContext` resolve to `Member` automatically, this is more or less for convenience, as many manually fetch the `Member` object of the author, and the `User` object is still accesible through `ctx.author.user`. Makes no sense to return the User when the author must be in the server if he sent a message with a command.~~
Adds a new `member` property on `CommandContext` that resolves to the `Member` of the author.
- [] This PR introduces some Breaking changes.
=> feat(CommandContext): add member property that resolves to Member of the author

src/types/slashCommands.ts
Discord added a shiny new NUMBER slash command option type that supports floating point numbers. I believe this is the only change needed in Harmony to support it, seeing as only complex types are being explicitly handled in `SlashCommandInteraction<T>()`.
=> feat(slash): Add NUMBER option type

mod.ts
Because comparing `Message.type` to numbers is ugly as hell.
=> fix(export): MessageTypes members not exported

src/managers/memberRoles.ts, src/rest/request.ts, src/structures/guild.ts, src/structures/member.ts, src/structures/webhook.ts
This PR fixes the rest doesn't send the `Content-Length` header when the body is undefined or null.
Very related to https://github.com/denoland/deno/issues/11920
Also, I removed all status checking codes since harmony will throw an error if the status is not 2xx.
=> fix(rest): not sending Content-Length header when the body is undefined

src/gateway/handlers/guildMemberUpdate.ts, src/structures/member.ts, src/types/endpoint.ts, src/types/gateway.ts, src/types/guild.ts, test/index.ts
Closes #241
Allows member server profile avatar fetching in a similar way to fetching user avatars. If no server profile avatar is set, it falls back to the underlying user's profile.
=> feat(member): Guild member avatar fetching

src/structures/message.ts
`msg.channel.send` was broken in https://github.com/harmonyland/harmony/commit/6d7786dcd09b7474607248a7582e726920d7624b due to the channel not being added to the message object. This fixes that.
=> fix(message): Set channel in message constructor

src/structures/member.ts, src/utils/colorutil.ts, test/index.ts
Adds a utility function for getting the member's effective (display) color, based on role positions. Also includes a fix to the color utility class, making sure that hex colors are padded to 6 characters in all situations.
=> feat(member): Add function for effective color

src/types/voice.ts
Follow up to #253 
Upstream pull request:
- https://github.com/discord/discord-api-docs/pull/3908
=> types(VoiceRegion): deprecated `vip` property

src/structures/interactions.ts
Interaction.reply() didn't take components into account when editing the response after the interaction had been deferred, so they would never show up under the message.
=> fix(interaction): use components after defer

mod.ts
Exports AuditLog-Types in mod.ts, so that they can be imported easily in own project to properly work with AuditLogs.
=> Export AuditLog-Types in mod.ts

.github/workflows/prettier.yml, src/structures/textChannel.ts, src/structures/webhook.ts
This fixes the constructor of the Webhook object, as well as introduces a method to fetch webhooks from a TextChannel
=> Fix latter 2 issues of #273

src/structures/channel.ts
Just easy way to delete channels
=> Channel: Add delete function

src/managers/guildChannels.ts
This pr fixes issue #293 
Adding override for `keys` method
=> Fix `GuildChannelsManager.keys()`

src/structures/member.ts
Adds setGuildTimeout and resetGuildTimeout functions to easily modify guild timeouts for a Member.
Previously, you could only do this by using Member.edit
=> feat(Member): set and reset guild timeouts

src/structures/member.ts, src/structures/role.ts, src/utils/permissions.ts
`Member` and `Role` structures both don't contain docs about actual usage of `permissions` property. Also, `Permissions` contains misleading docs about itself, which implies that the `Permissions` class uses the Rest API when it actually doesn't.
=> Update misleading docs for `permissions` property

src/structures/channel.ts, src/structures/message.ts
This pull requests adds a url field for the Message structure which is a link for the message
and adds the .setCategory function for all guild channels
=> Add a url field to messages and add .setCategory function for guild channels

src/commands/client.ts, test/class.ts
This adds regex prefixes to the CommandClient and adds one in /test/class.ts. It addresses #306.
=> feat(commands): add regular expression prefixes

src/types/gateway.ts
Closes #326
Adds the MESSAGE_CONTENT intent which was recently required
=> Add MESSAGE_CONTENT intent

src/commands/command.ts, src/structures/channel.ts
One of the older pull requests broke current code so this pr fixes it. There was also an issue where command manager didn't properly supplied the name.
`.add` method adds command to collection with suffix. That suffix wasn't included in the remove method.
=> Fix deno and command manager issues

src/managers/guildEmojis.ts, src/structures/webhook.ts
This PR adds:
- GuildEmojiManager.fetchAll: Fetch all emotes in a server
- Webhook.create: Create a webhook in a channel
=> Add: GuildEmojiManager.fetchAll and Webhook.create

src/gateway/handlers/guildAuditLogEntryCreate.ts, src/gateway/handlers/mod.ts, src/structures/guild.ts, src/types/gateway.ts
This pr implements [audit log create event](https://discord.com/developers/docs/change-log#guild-audit-log-events).
> noticed that typings for `AuditLogEntry` were incorrect, im not really sure if i should fix them in this pr or not or if they are supposed to be like that
=> feat: add audit log create event

src/commands/client.ts, src/structures/member.ts
This pr fixes:
- Guild Owner getting a permission error when executing a command
- Member object always returns default permissions and doesn't include role permissions
It's possible that the perms might desync if roles get modified. Feel free to let me know where/how I should implement a fix for that.
=> Fix: Incorrect permissions in the member object & in commands

src/gateway/handlers/messageCreate.ts, src/interactions/client.ts, src/rest/endpoints.ts, src/structures/applicationCommand.ts, src/types/applicationCommand.ts
This also fix invalid typings for some files
=> Add missing option type

mod.ts, src/commands/client.ts, src/commands/command.ts, src/gateway/handlers/mod.ts
This command adds the `commandOnCooldown` event, along with a `cooldown` property on both `CommandClient` and `Command`
=> Add command cooldowns

src/client/client.ts, src/structures/textChannel.ts
This adds the `defaultAllowedMentions` property to `Client` so you can set default mentions to fallback on when they aren't provided. This should work similar to how libraries like discord.js do it.
=> Add default mentions for messages

src/utils/colorutil.ts
This fix makes the random hex method no longer sometimes return an invalid color code due to generating an invalid length hex code.
=> Fix: Prevent invalid color codes from being generated

src/managers/messageReactions.ts, src/structures/textChannel.ts
This pr adds option to pass emoji with enclosing `<>`, both to `<TextChannel>.addReaction` and `<TextChannel>.removeReaction`. Earlier harmony didn't said explicitly that it expects emoji strings without `<>`.
=> Support 'raw' emojis

src/structures/member.ts, src/structures/user.ts, src/types/user.ts
This adds discord's display name property to the user class and also changes `tag` to return their "handle" if they don't have a discriminator
=> Feat: Display name support

src/structures/webhook.ts
Add components to webhook message payload allowing to send application-owned webhooks to send components.
Fixes: #360
=> Add components to webhooks messages

src/gateway/handlers/voiceStateUpdate.ts
Fixes a bug where voice state update events didn't always set the member cache, leading to the `user` and `member` properties on `VoiceState` objects being missing.
=> Fix voice state update sometimes not setting the member cache

src/interactions/client.ts, src/interactions/commandModule.ts, src/interactions/decorators.ts, test/slash.ts
Adds component interaction decorator
Solves #322
=> Add component interaction decorators

src/structures/member.ts
This PR makes server owners have all permissions by default as currently checking for items such as admin would return false even though the owner would have it.
Possibly fixes #369? I'm not 100% sure if this is what was meant given my testing seems to show all users correctly other than owner
=> Fix: Server Owner perms are reported wrong

src/commands/command.ts, src/commands/extension.ts
Closes #137
Adds a `loadDirectory` method on the `ExtensionManager` thus allowing loading similar to the way you can with commands.
=> Feat: Extension directory loading

src/structures/messageMentions.ts
Closes #370 
Skips fetching channel info if `this.client` is undefined as is the case in a webhook message thus not causing a crash
=> Fix: Error thrown from channel mention in webhook

src/rest/request.ts
Handle `message.file` and `message.files` of type `GuildForumChannel` in REST request.
=> Fix: No files sent when creating a thread in forum
